name: "Cronjob"

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight UTC
  workflow_dispatch: # allow manual run

jobs:
  update-quote:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Generate README from template
        run: go run .

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update daily quote"
          git push origin main
